name: meal_tracker_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_analytics: ^11.4.6
  permission_handler: ^12.0.0+1
  flutter_launcher_icons: ^0.14.3
  image_picker: ^1.1.2
  share_plus: ^11.0.0
  firebase_storage: ^12.4.6
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/AppIcon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/AppIcon.png"
